import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Button from './components/Button';
import React, { useState } from "react";

export default function Home() {
  const [count, setCount] = useState<number>(0);

  const handleIncrement = () => {
    setCount(count + 1);
  };

  const handleDecrement = () => {
    setCount(count - 1);
  };

  return (
    <>
      <Head>
        <title>Next First Activity</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            SWRTech&nbsp;
            <code className={styles.code}>Software Development Services</code>
            <p className={styles.subtitle}>M Y  F I R S T  A C T I V I T Y  F O R</p>
            <p className={styles.title}>NEXT.js</p>
            <p className={styles.task}>task:</p>
            <p className={styles.direction}>Create a button that, when clicked, increments a counter and displays the 
              current count. Add some basic styling to make the button stand out.</p>
          </p>

          <div className={styles.center}>
            <div className={styles.buttoncon}>
              <div>
                <Button name={'+'} onPress={() => handleIncrement()} />
              </div>
              <div>
                <Button name={'-'} onPress={() => handleDecrement()} />
              </div>
            </div>
            <div>
              <p>{count}</p>
            </div>
          </div>

          <div>
            <Image
              src="/nico.png"
              alt="nicolai"
              className={styles.vercelLogo}
              width={75}
              height={350}
              priority
            />
          </div>
        </div>
      </main>
    </>
  )
}
